### ISSUE TITLE
Empty Strings When Using PhraseLocalizations

### ISSUE THREAD

**Issue by jordanmlacalle** [phrase/phrase-flutter-sdk#1]
### Environment
**flutter**: 3.0.5
**phrase package**: 1.0.4

### Issue
We are currently evaluating the use of Phrase Strings for copy and translation management for our Flutter App at the company I work for.

We have 12 languages currently setup in Phrase and I have followed the guides here:
https://pub.dev/packages/phrase
https://support.phrase.com/hc/en-us/articles/5808300599068-Using-the-CLI-Strings-

After running the proper Phrase CLI commands and then `flutter pub run phrase`, I have a properly populated **lib/l10n** folder and can see that **.dart_tool/flutter_gen/gen_l10n** is also properly populated with the generated Dart code.

When using the PhraseLocalizations class to setup localizations in the app:
```
        localizationsDelegates: PhraseLocalizations.localizationsDelegates,
        supportedLocales: PhraseLocalizations.supportedLocales,
```
All localized Strings in the app are empty and result in some rendering errors from the Flutter engine.

If I instead choose to use the AppLocalizations class, generated by the Flutter localizations tools, the localized Strings (pulled from Phrase) are displayed as expected with no errors.

The OTA feature of Phrase Strings looked appealing so we would like to be able to use that, but right now it seems we'll need to use this workaround of using `AppLocalizations` as before.

Thanks for any assistance!

**Comment by theSoenke** [comment]
Hi @jordanmlacalle, thanks for reporting this issue. This definitely does not sound right and it should work out of the box. I'll make sure we investigate what might cause this. Could you also share your distribution id and environment token at support@phrase.com or in the chat on phrase.com with a link to this GitHub issue? That would help to take a closer look

**Comment by jordanmlacalle** [comment]
@theSoenke Sorry for the long delay! I'll check if we still have this issue and let you know. Up to this point we have been using the workaround mentioned above, which would not allow for OTA copy updates.

If we still have the issue then I'll contact support with the info requested, otherwise I'll close the issue. Thanks!
