### ISSUE TITLE
Feature request: Provide timeout Duration parameter to setup method.

### ISSUE THREAD

**Issue by tsinis** [phrase/phrase-flutter-sdk#4]
Hey Phrase Team!

We are having issues with Phrase fetching the updates with a very poor internet connection, basically, users have to wait for about 1 minute in order to start the app. It uses the default 30-sec timeout for OTA fetch requests.

Here is how to replicate the issue:

To simulate a bad internet connection on your iPhone:

1. Open the Settings app and navigate to the Developer option.
2. Select the Network Link Conditioner under the NETWORKING option.
3. Now enable the Network Link Conditioner & choose the network profile "`100% Lost`"
4. Build a Flutter app with `Phrase.setup(checkForUpdates: true, ...)`; before runApp.

There should be a way to reduce this time (for example with an additional `Duration timeoutDuration` parameter in the Phrase.setup call). Thanks!

**Comment by theSoenke** [comment]
Hey @tsinis! Thanks for the good suggestion. The iOS and Android SDK already offer a timeout param and this should be added to the Flutter SDK as well. I'll create a task for this. Still what we usually recommend is to update the translations in the background and not wait until the app has been started. The translations would then be available on the next app start

**Comment by tsinis** [comment]
> Hey @tsinis! Thanks for the good suggestion. The iOS and Android SDK already offer a timeout param and this should be added to the Flutter SDK as well. I'll create a task for this. Still what we usually recommend is to update the translations in the background and not wait until the app has been started. The translations would then be available on the next app start

Hey, @theSoenke thanks! By updating in the background, do you mean to run the `Phrase.setup` after app initialization or run it twice (also after MaterialApp init?)? Because I'm pretty sure I was doing it also, but for some reason, I didn't see the Phrase Debug messages about OTA requests in my debugger this way.

**Comment by theSoenke** [comment]
Perfect! I'll also try to make sure that something like this is part of the example app to demonstrate it https://github.com/phrase/flutter_sdk_example

**Comment by theSoenke** [comment]
With the latest release 2.2.0 it's now also possible to pass a timeout to `setup` and `updateTranslations` https://pub.dev/packages/phrase/changelog
