### ISSUE TITLE
Placeholders not translated and wrongly displayed with << >>

### ISSUE THREAD

**Issue by javi-appinio** [phrase/phrase-flutter-sdk#5]
Hey Phrasers!

From a couple of days I've noticed that new created placeholder params (with brackets) are being translated to `<<user>>`

the *.arb files are looking ok, with brackets, but when translating the translation isn't as expected

Pharse key:
![image](https://github.com/phrase/phrase-flutter-sdk/assets/106824952/eb5dbd54-0d68-4f0d-b2a6-41612ff615d9)

arb file
![image](https://github.com/phrase/phrase-flutter-sdk/assets/106824952/aede1660-c47f-48d4-ae1b-1be6845d4a8a)

use of it (checked that we are passing a string with a valid value
![image](https://github.com/phrase/phrase-flutter-sdk/assets/106824952/3f230479-bb41-4f22-8952-ac56824cb83b)

result on the screen
![image](https://github.com/phrase/phrase-flutter-sdk/assets/106824952/7cbf5699-8ee3-492b-aae2-863236b95737)

Any idea of what's going on?
Thanks in advance!

**Comment by felixssimoes** [comment]
I cannot reproduce this behavior. I created a similar translation entry in a test arb file and the output result is as expected. Just to be sure I did not include the placeholder type in the German translation (which should not matter as it defaults to `String` anyway).

This is the English arb:
```arb
"emptyStateNoPollsAskedDescrip": "Follow {nameOfUser} and ask your first question!",
  "@emptyStateNoPollsAskedDescrip": {
    "type": "text",
    "description": "Empty state description",
    "placeholders": {
      "nameOfUser": {
        "type": "String"
      }
    }
  },
```
And this is the German one:
```arb
"emptyStateNoPollsAskedDescrip": "Folgen Sie {nameOfUser} und stellen Sie Ihre erste Frage!",
  "@emptyStateNoPollsAskedDescrip": {
    "type": "text",
    "placeholders": {
      "nameOfUser": {}
    }
  },
```
This is how the generated translation code in `phrase_localizations.dart` looks like:
```dart
  @override
  String emptyStateNoPollsAskedDescrip(String nameOfUser) =>
      Phrase.getText(localeName, 'emptyStateNoPollsAskedDescrip',
          {'nameOfUser': nameOfUser}) ??
      _fallback.emptyStateNoPollsAskedDescrip(nameOfUser);
```
And this is how it looks like in `app_localizations_en.dart`:
```dart
  @override
  String emptyStateNoPollsAskedDescrip(String nameOfUser) {
    return 'Follow $nameOfUser and ask your first question!';
  }
```
And the German counterpart:
```dart
  @override
  String emptyStateNoPollsAskedDescrip(String nameOfUser) {
    return 'Folgen Sie $nameOfUser und stellen Sie Ihre erste Frage!';
  }
```
It is then used this way:
```dart
            Text(AppLocalizations.of(context)
                .emptyStateNoPollsAskedDescrip('John')),
```

And this is how it looks in the app:
<img width="341" alt="Screenshot 2024-02-19 at 09 53 22" src="https://github.com/phrase/phrase-flutter-sdk/assets/1503250/5635e7a0-8791-4330-ad65-a53055ea56b8">


@javi-appinio Could you please double check this key files in your code and check how does it look like on you side and let us know if you found anything out of place? Thank you

**Comment by javi-appinio** [comment]
The code looks exactly the same, but I've managed to solve it by creating a new key from scratch. Now I can substitute my placeholder as usual.

I guess something was misconfigured in that key's placeholder in our Phrase setup.

Many thanks for your help!!
